name: Docker Image CICD

on:
  push:
    branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/platox-ai-api:latest
    # - name: Login To Docker Hub
    #   run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
    # - name: Push Docker Image to Docker Hub
    #   run: docker push ${{ secrets.DOCKER_USERNAME }}/platox-ai-api:latest
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/platox-ai-img
    
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: 'placeholder'
        # if_key_exists: replace # replace / ignore / fail; optional (defaults to fail)
    - name: Adding Known Hosts
      run: ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Server Refresh Container
      run: echo ${{ secrets.SUDO_PASS }} | ssh -tt ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} ${{ secrets.HOST_COMMAND }}
